swagger: "2.0"
info:
  description: Ceci est le fichier swagger correspondant à nôtre API
  version: "1.0.0"
  title: Swagger pour API ReST
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Chemins supportés
paths:
  /people:
    get:
      operationId: people.read
      tags:
        - People
      summary: Structure de données people sous-jacente
      description: Lire la liste des personnes people
      responses:
        200:
          description: Succès dans la lecture des données
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string
                timestamp:
                  type: string
